name: CD Chart Deployment
 
on:
  workflow_dispatch:    
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Helm
        uses: azure/setup-helm@v2
        with:
          version: 'latest'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: execute py script # run main.py
        run: python script.py